# Generated by Django 4.2.12 on 2024-09-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
