# Generated by Django 4.2.12 on 2024-09-14 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('wallet_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_id', models.CharField(editable=False, max_length=13, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('destination_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('crypto_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cryptocoin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('escrow_fee_payer', models.CharField(blank=True, choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('BOTH', '50/50')], default='BOTH', max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cryptocoin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(editable=False, max_length=5, unique=True)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('seller_email', models.EmailField(max_length=254)),
                ('buyer_token_quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('seller_token_quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('escrow_fee_payer', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('BOTH', '50/50')], default='BOTH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer_deposit_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('seller_deposit_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('fee_payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('buyer_crypto_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_crypto', to='core.cryptocoin')),
                ('seller_crypto_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_crypto', to='core.cryptocoin')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('release', models.BooleanField(default=False)),
                ('dispute_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.trade')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=15, prefix='', unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('crypto_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cryptocoin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
