# Generated by Django 4.2.12 on 2024-09-14 10:40

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='withdraw_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=15, prefix='', unique=True),
        ),
    ]
