# Generated by Django 4.2.12 on 2024-09-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_withdrawal_withdraw_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoin',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cryptocoins/'),
        ),
    ]
