# Generated by Django 4.2.12 on 2024-09-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cryptocoin_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
