# Generated by Django 4.2.12 on 2024-09-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deposit_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_method',
            field=models.CharField(choices=[('crypto', 'Cryptocurrency'), ('bank', 'Bank Transfer')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='crypto_coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cryptocoin'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
